"""Original worked examples paired with the fixed MenuNori practice menu."""

SUPPLEMENTS = {
    'korean-kiosk': '''<h2>A screen-by-screen example: one mild tteokbokki</h2><p>Suppose you are eating at the shop and want one mild tteokbokki with cheese. Start with <span lang="ko">매장</span>, open <span lang="ko">떡볶이</span>, select <span lang="ko">순한맛</span>, and select <span lang="ko">치즈 추가</span>. Add one portion. Your basket should show one dish, two option labels, and ₩5,500. That total is the base price plus one extra, not two dishes.</p><p>If the basket says <span lang="ko">치즈떡볶이</span> instead, you chose the separate cheese dish. On our menu it has the same price, but it does not demonstrate the extra-option step. Go back to the menu and choose the intended entry. The useful habit is to read the line you actually added, rather than relying on the photograph or total.</p><details class="knowledge-check"><summary>Quick check: does “결제” mean review the basket?</summary><p>No. <span lang="ko">결제</span> refers to payment. <span lang="ko">확인</span> means check or confirm, but its effect depends on the current screen. Read the surrounding labels before pressing a real kiosk’s final button.</p></details>''',
    'dine-in-takeaway': '''<h2>One order, two different intentions</h2><p>Compare these practice slips. Both contain the same food and cost ₩7,000, but only the second matches a takeaway mission.</p><div class="example-pair"><div><h3>Eating at the shop</h3><p lang="ko">매장<br>김밥 × 1<br>군만두 × 1</p><p>You expect to eat here. The unchanged price does not turn this into a takeaway order.</p></div><div><h3>Taking the food away</h3><p lang="ko">포장<br>김밥 × 1<br>군만두 × 1</p><p>You expect packed food. Read the mode line before the item names.</p></div></div><h2>When pointing is clearer than explaining</h2><p>If you cannot pronounce the word confidently, show the <span lang="ko">포장</span> label and say <span lang="ko">포장해 주세요</span>. If the staff member asks a follow-up question you cannot understand, use a translation app. Memorizing these two words helps you start the interaction; it does not mean you need to understand every reply.</p><details class="knowledge-check"><summary>Quick check: your food is right, but the slip says 매장. Is mission 1 complete?</summary><p>No. Switch the mode to <span lang="ko">포장</span>. You can keep the correct dishes in your basket and change only the order type.</p></details>''',
    'read-korean-menu': '''<h2>Read a menu line from left to right</h2><div class="menu-example"><span lang="ko">치즈떡볶이</span><span>₩5,500</span></div><p>First find the whole dish name: cheese tteokbokki. Then read the amount: one listed menu unit is ₩5,500 in our shop. There is no <span lang="ko">추가</span> label on this line, because cheese is part of the named dish. An options screen can still ask about spice.</p><div class="menu-example"><span lang="ko">떡볶이 / 치즈 추가</span><span>₩4,500 + ₩1,000</span></div><p>This line has two parts: the base dish and an extra. Adding them gives ₩5,500 for one configured portion. The equal totals do not make the two menu entries identical. For a practice mission, match both the name and the requested option.</p><h2>Build a small recognition list</h2><p>Choose three words you can identify without translation: <span lang="ko">김밥</span>, <span lang="ko">라면</span>, and <span lang="ko">포장</span>. Find them in the game, say their English meanings, and then check the guide. Learning a small set accurately is more useful than guessing at an entire menu.</p><details class="knowledge-check"><summary>Quick check: does a dumpling photo tell you how many pieces you will receive?</summary><p>No. Read the menu’s portion or piece information. MenuNori uses a fictional menu portion and does not specify a real restaurant’s piece count.</p></details>''',
    'spice-and-extras': '''<h2>What happens when you order two portions?</h2><p>In MenuNori, options belong to a configured item. Two mild tteokbokki portions with extra cheese cost 2 × (₩4,500 + ₩1,000) = ₩11,000. It would be an error to calculate 2 × ₩4,500 + ₩1,000, which adds cheese to only one portion. At a real restaurant, follow the option quantity and total shown on its screen.</p><p>If two people want different spice levels, add two separate lines: one mild portion and one regular portion. Changing the quantity of a mild line to two gives you two mild portions. This is why an option label matters as much as the quantity.</p><h2>A request and an available option are different</h2><p>Our game always lets you choose its listed options. A restaurant may have a fixed recipe, a sold-out extra, or a required set choice. If there is no mild option, asking staff is reasonable; inventing an option by selecting a different topping will not change the sauce. Use the game to recognize the choice when it exists.</p><details class="knowledge-check"><summary>Quick check: is mild tteokbokki the same as a non-spicy dish?</summary><p>No. In this practice shop it still contains heat. Mission 1 asks for non-spicy choices; mission 2 asks you to change the spice option on a spicy dish.</p></details>''',
    'check-your-order': '''<h2>Find the mistake in this slip</h2><div class="practice-slip"><p class="eyebrow">FICTIONAL ORDER TO CHECK</p><p lang="ko">매장<br>라면 × 1 — 보통맛<br>군만두 × 2</p><p>Total: <strong>₩11,000</strong></p></div><p>The mission asks for two ramyeon portions and one dumpling portion. The slip contains three menu units, which sounds right if you only look at the cart badge. The quantities are reversed. Correcting the lines changes the total to ₩11,500: 2 × ₩4,000 plus ₩3,500.</p><h2>If you have already paid</h2><p>Keep the receipt or order number and speak to staff. Show the specific line that is wrong, rather than starting another paid order on the machine. Whether an order can be changed depends on the restaurant and whether preparation has started. MenuNori gives unlimited retries because no real food or payment is involved.</p><details class="knowledge-check"><summary>Quick check: does the right total prove you chose the right dishes?</summary><p>No. Two different combinations can have the same total. Check the order type, names, quantities, and options before using the amount as your last check.</p></details>'''
}

EXTRA_GUIDES = [
('quantity-and-prices', 'Korean Menu Prices and Portions: Won, 개 and 인분',
 'Understand Korean menu prices in won and quantity labels 수량, 개 and 인분. Work through sample totals and distinguish individual pieces from portions.', '''
<p class="lead">A plus button changes a number. The important question is what that number counts. One menu item might be a bowl, a roll, a set, or a portion containing several pieces.</p>
<h2>Separate the price from the unit</h2><p>In our fictional shop, <span lang="ko">김밥</span> is listed at ₩3,500. Selecting quantity 2 means two menu units and a total of ₩7,000. <span lang="ko">군만두</span> is also ₩3,500, but one menu unit is a portion of dumplings. The matching prices do not mean the portions contain the same number of pieces.</p><p>At an actual restaurant, read any unit information beside the name or in the description. A photograph can show a serving suggestion. It should not be your only evidence for a piece count or a serving size.</p>
<h2>Three quantity labels worth recognizing</h2><table><thead><tr><th scope="col">Label</th><th scope="col">Meaning</th><th scope="col">What to check</th></tr></thead><tbody><tr><td lang="ko">수량</td><td>Quantity</td><td>The number of menu units in this basket line</td></tr><tr><td lang="ko">개</td><td>Pieces or count</td><td>Which object is being counted</td></tr><tr><td lang="ko">인분</td><td>Servings</td><td>The stated serving size and any minimum order</td></tr></tbody></table><p>For example, <span lang="ko">6개</span> describes a count of six; <span lang="ko">2인분</span> describes two servings. A restaurant can also list a minimum order separately. MenuNori does not simulate minimum-order rules, shared hotpots, or set menus, so read those conditions on the real menu.</p>
<h2>Read the comma in a won price</h2><p>₩4,500 means four thousand five hundred won. The comma separates thousands; it is not a decimal point. A menu may use the symbol ₩ or the Korean word <span lang="ko">원</span>. Within this exercise, ₩4,500 and 4,500원 express the same amount.</p><p>Use the menu’s amount directly when checking your basket. A currency conversion is a separate estimate and can change with exchange rates and fees. MenuNori does not provide live conversions or represent typical current restaurant prices.</p>
<h2>Work out a complete order for two</h2><p>Mission 3 gives you a ₩12,000 ceiling. You need two regular ramyeon portions and one dumpling portion. Write the quantities before calculating the total.</p><table><thead><tr><th scope="col">Dish</th><th scope="col">Unit price</th><th scope="col">Quantity</th><th scope="col">Line total</th></tr></thead><tbody><tr><td lang="ko">라면</td><td>₩4,000</td><td>2</td><td>₩8,000</td></tr><tr><td lang="ko">군만두</td><td>₩3,500</td><td>1</td><td>₩3,500</td></tr></tbody></table><p>The basket total is ₩11,500, leaving ₩500 below the mission’s ceiling. You have three menu units, but only two distinct dish names. A cart count and a count of basket lines answer different questions.</p>
<h2>Include extras inside the multiplication</h2><p>One tteokbokki with extra cheese costs ₩4,500 + ₩1,000 = ₩5,500 in our simulation. Two of that configured item cost 2 × ₩5,500 = ₩11,000. The extra is attached to each portion. If only one person wants cheese, add one line with cheese and another without it; the combined amount is ₩10,000.</p><p>Read both option lines before confirming. Our game combines identical configurations into one line and keeps different configurations separate. A real kiosk may present the same information differently.</p>
<h2>A quick exercise before you travel</h2><p>Calculate one gimbap and two dumpling portions from this menu. Then compare your answer with the basket in the game. If the amounts disagree, inspect the quantities before assuming the machine is wrong.</p><details class="knowledge-check"><summary>Show the calculation</summary><p>₩3,500 + 2 × ₩3,500 = ₩10,500. This contains one gimbap menu unit and two dumpling portions. It does not satisfy mission 1, which asks for only one dumpling portion.</p></details><p class="note">Every amount in this article belongs to MenuNori’s fictional menu. The restaurant you visit is the source for actual prices, portion sizes and charges.</p>'''),
('restaurant-ordering-phrases', 'How to Order Food in Korean: Restaurant Phrases',
 'Learn simple Korean restaurant phrases for ordering food, asking for takeaway and getting help. Read English meanings and worked ordering examples.', '''
<p class="lead">You do not need to deliver a memorized speech. Pointing to a dish and using one clear request can be enough to start. These examples help you say what you want and notice when you need help.</p>
<h2>Start with the dish and 주세요</h2><div class="phrase"><strong lang="ko">김밥 하나 주세요.</strong><small>One gimbap, please.</small></div><p>The pattern is dish + quantity + <span lang="ko">주세요</span>, a polite request to give you something. <span lang="ko">하나</span> means one here. The menu determines what one unit contains. For gimbap in our shop it is one roll; for dumplings it is one listed portion.</p><p>If you are pointing rather than naming the dish, <span lang="ko">이거 하나 주세요</span> means “One of this, please.” Make the reference clear: point to the actual menu entry, not just a broad photograph containing several dishes.</p>
<h2>Add your order type</h2><div class="phrase"><strong lang="ko">김밥 하나 포장해 주세요.</strong><small>One gimbap to go, please.</small></div><div class="phrase"><strong lang="ko">여기서 먹고 갈게요.</strong><small>I’ll eat here.</small></div><p>Choose the version that matches your plan. If the machine already asks <span lang="ko">매장</span> or <span lang="ko">포장</span>, make the same choice on screen. Saying “to go” while leaving dine-in selected creates two conflicting signals; check the basket before paying.</p>
<h2>Use a question when you are unsure</h2><div class="phrase"><strong lang="ko">이거 뭐예요?</strong><small>What is this?</small></div><div class="phrase"><strong lang="ko">이거 매워요?</strong><small>Is this spicy?</small></div><p>A question is useful only if you can understand enough of the reply to act on it. A translation app can help with the answer. For spice, staff may describe the flavor relative to their restaurant’s usual recipe. If you are unsure, ask again or choose another dish.</p><p>These questions are not an ingredient check. If you need to avoid an ingredient, show its exact name and ask the restaurant about the actual food. This page does not provide an allergy translation card or a guarantee about recipes.</p>
<h2>Ask for help with the machine</h2><div class="phrase"><strong lang="ko">주문하는 것 좀 도와주세요.</strong><small>Please help me place an order.</small></div><p>Use this when you cannot understand a screen or return to the previous step. Show the screen you are stuck on. Staff assistance is often more useful than pressing buttons experimentally, especially near payment. Availability and service arrangements vary by restaurant.</p>
<h2>Two small example exchanges</h2><div class="conversation"><h3>A takeaway order</h3><p><strong>You:</strong> <span lang="ko">김밥 하나 포장해 주세요.</span><br><span class="translation">One gimbap to go, please.</span></p><p><strong>Staff:</strong> <span lang="ko">김밥 하나요?</span><br><span class="translation">One gimbap?</span></p><p><strong>You:</strong> <span lang="ko">네.</span><br><span class="translation">Yes.</span></p></div><p>In this invented exchange, the staff repeats the dish and quantity. Listen for the part you recognize and check it before agreeing. A real reply can be longer or ask about another option.</p><div class="conversation"><h3>Changing the order type</h3><p><strong>You:</strong> <span lang="ko">포장으로 바꿀 수 있어요?</span><br><span class="translation">Can I change this to takeaway?</span></p><p><strong>Staff:</strong> <span lang="ko">네, 포장이요.</span><br><span class="translation">Yes, takeaway.</span></p></div><p>This is an example of a successful request, not a promise that changes are always possible. Ask before payment when you can. If you already paid, keep your order number and explain the specific change to staff.</p>
<h2>Rehearse one phrase with one decision</h2><p>Complete mission 1 and read <span lang="ko">김밥 하나 포장해 주세요</span> while checking your basket. You are connecting a phrase to a real choice on screen. Then switch to dine-in and practice <span lang="ko">여기서 먹고 갈게요</span>. The goal is to understand the intention, rather than repeat sounds without knowing what you ordered.</p><p class="note">The Korean examples are fixed learning content. Romanization and audio are not provided; this page does not grade pronunciation. Independent native-speaker review is not claimed. See our <a href="/editorial/">content and corrections policy</a>.</p>''')
]
